
//----------------------------------------------------
// The following code was generated by CUP v0.10f
// Thu Dec 13 10:01:50 CST 2018
//----------------------------------------------------

/** Cup generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int STRLIT = 5;
  static final int rw_WHILE = 24;
  static final int rw_BOOL = 23;
  static final int LBRACKET = 31;
  static final int INCREMENT = 48;
  static final int rw_IF = 17;
  static final int SLASH = 42;
  static final int rw_CONTINUE = 46;
  static final int rw_FALSE = 41;
  static final int LPAREN = 8;
  static final int SEMI = 7;
  static final int rw_PRINT = 26;
  static final int rw_TRUE = 44;
  static final int DECREMENT = 49;
  static final int MINUS = 14;
  static final int RPAREN = 9;
  static final int NOT = 47;
  static final int AND = 20;
  static final int rw_VOID = 36;
  static final int INTLIT = 3;
  static final int LT = 33;
  static final int rw_CONST = 32;
  static final int OR = 21;
  static final int COMMA = 38;
  static final int rw_ELSE = 43;
  static final int GEQ = 39;
  static final int PLUS = 13;
  static final int rw_READ = 27;
  static final int rw_INT = 22;
  static final int EOF = 0;
  static final int RBRACKET = 30;
  static final int error = 1;
  static final int COR = 18;
  static final int rw_CLASS = 28;
  static final int rw_RETURN = 35;
  static final int EQ = 15;
  static final int ASG = 10;
  static final int TIMES = 37;
  static final int CHARLIT = 4;
  static final int COLON = 25;
  static final int LBRACE = 11;
  static final int rw_CHAR = 34;
  static final int RBRACE = 12;
  static final int CAND = 19;
  static final int LEQ = 40;
  static final int rw_BREAK = 45;
  static final int INT_BITSTR = 6;
  static final int GT = 29;
  static final int NOTEQ = 16;
  static final int IDENTIFIER = 2;
}

